// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXd6yVKHGIl_5AWkMnSsdqLZ0CS5FbjCc',
    appId: '1:350333603663:web:e54deea0d7427c50c8ff3a',
    messagingSenderId: '350333603663',
    projectId: 'chat-app-459af',
    authDomain: 'chat-app-459af.firebaseapp.com',
    storageBucket: 'chat-app-459af.firebasestorage.app',
    measurementId: 'G-2PK2LDNQNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACEncBqd0oYKcRHpzVStld8J_cG7Q9tjE',
    appId: '1:350333603663:android:6000f28ae0b757d6c8ff3a',
    messagingSenderId: '350333603663',
    projectId: 'chat-app-459af',
    storageBucket: 'chat-app-459af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCavwpM1Zs7fMdcXnsWhBPSpdgoZY5uO2c',
    appId: '1:350333603663:ios:9bb395cc7bf1fcbbc8ff3a',
    messagingSenderId: '350333603663',
    projectId: 'chat-app-459af',
    storageBucket: 'chat-app-459af.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCavwpM1Zs7fMdcXnsWhBPSpdgoZY5uO2c',
    appId: '1:350333603663:ios:9bb395cc7bf1fcbbc8ff3a',
    messagingSenderId: '350333603663',
    projectId: 'chat-app-459af',
    storageBucket: 'chat-app-459af.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXd6yVKHGIl_5AWkMnSsdqLZ0CS5FbjCc',
    appId: '1:350333603663:web:23ffd727bfeb3ef4c8ff3a',
    messagingSenderId: '350333603663',
    projectId: 'chat-app-459af',
    authDomain: 'chat-app-459af.firebaseapp.com',
    storageBucket: 'chat-app-459af.firebasestorage.app',
    measurementId: 'G-84CVCPVK2J',
  );

}